version: '3'

volumes:
    database-data:
networks:
    idea2app:

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${APP_SECRET}
        volumes:
            - database-data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - idea2app
        restart: always
    rest-node-ts:
        depends_on:
            - postgres
        build: ./server
        image: idea2app/rest-node-ts
        environment:
            - NODE_ENV=production
            - DATABASE_URL=postgres://postgres:${APP_SECRET}@postgres:5432/postgres
            - PORT=8080
        ports:
            - 8080:8080
        networks:
            - idea2app
        restart: always
    next-bootstrap-ts:
        depends_on:
            - rest-node-ts
        build: ./browser
        image: idea2app/next-bootstrap-ts
        environment:
            - NODE_ENV=production
            - PORT=3000
        ports:
            - 3000:3000
        networks:
            - idea2app
    caddy:
        depends_on:
            - next-bootstrap-ts
        image: caddy
        ports:
            - 80:80
            - 443:443
        networks:
            - idea2app
        command: caddy reverse-proxy --from your.domain.com --to next-bootstrap-ts:3000
